[supervisord]
nodaemon=true

[program:gunicorn]
command=/bin/sh -c "gunicorn --workers=9 --bind=0.0.0.0 --timeout 600 --keep-alive=5 --worker-class=gevent --preload ws:app --chdir /home/site/wwwroot"
directory=/home/site/wwwroot
autostart=true
autorestart=true
stderr_logfile=/home/site/wwwroot/logs/gunicorn.err.log
stdout_logfile=/home/site/wwwroot/logs/gunicorn.out.log
